name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm typecheck

  test:
    name: Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test

  actions-timeline:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2
