name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm typecheck

  actions-timeline:
    needs: [lint]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - uses: Kesin11/actions-timeline@v2
